### ISSUE TITLE
一个 Bug 和 一个建议

### ISSUE THREAD

**Issue by duobei** [PyHubCC/pyhub.cc#3]
- 一个 Bug

输入框输入的时候，提示字符可以不显示了 

![bug](https://cloud.githubusercontent.com/assets/926853/15494674/55ae7bea-21be-11e6-8800-2f2ed523edcf.png)

![bug-1](https://cloud.githubusercontent.com/assets/926853/15494710/8f001aa2-21be-11e6-860e-4d199c6b4eee.png)

- 一个建议

分享与 Python 相关的链接的时候只需要输入一个链接就好了，其他抓取就行。

**Comment by rainyear** [comment]
@duobei 非常感谢~输入框的问题应该是CSS没有加载完成造成的，后面会优化一下缓存。抓取问题会解决的~

**Comment by rainyear** [comment]
Site Updated~
